/**
 * Discovery taxonomy: the food/CPG supplier categories behind the
 * category-first discovery surfaces.
 *
 * This is deliberately a NEW module, separate from the nine-family packaging
 * taxonomy (src/taxonomy) — that one classifies packaging listings for search
 * and RFQs; this one classifies real supplier records from the Platform Ready
 * directory. They share no slugs and no code paths.
 *
 * Keyword rules were scored against the real workbook (7,658 records): each
 * keyword anchors a category, and the import report is the tuning dial —
 * tuning is a data edit here, never a classifier code change.
 */

export interface DiscoveryCategory {
  /** URL key, e.g. "dairy" → /categories/dairy. */
  slug: string;
  /** Card and page heading, e.g. "Dairy & Cheese". */
  name: string;
  /** One-line card copy. */
  description: string;
  /** Keyword anchors, matched case-insensitively on word boundaries. */
  keywords: string[];
  /** Committed artwork path, e.g. "/discovery/dairy.jpg". */
  image: string;
}

/** Zero-match fallback: every record stays reachable and every count honest. */
export const OTHER_GENERAL_SLUG = "other-general";

export const DISCOVERY_CATEGORIES: readonly DiscoveryCategory[] = [
  {
    slug: "dairy",
    name: "Dairy & Cheese",
    description: "Milk, cheese, yogurt & whey producers",
    keywords: [
      "dairy",
      "cheese",
      "milk",
      "yogurt",
      "yoghurt",
      "whey",
      "lactose",
      "creamery",
      "butter",
      "kefir",
      "ice cream",
      "cheesemaker",
      "cheeses",
    ],
    image: "/discovery/dairy.jpg",
  },
  {
    slug: "beverages",
    name: "Beverages",
    description: "Juice, soda, water & drink co-packers",
    keywords: [
      "beverage",
      "beverages",
      "juice",
      "soda",
      "kombucha",
      "sparkling",
      "bottled water",
      "energy drink",
      "soft drink",
      "sports drink",
      "drink mix",
      "lemonade",
      "hydration",
      "sports nutrition drink",
      "drink",
      "drinks",
      "juices",
      "sodas",
      "seltzer",
      "cider",
      "smoothie",
      "smoothies",
      "nectar",
      "tonic",
      "spring water",
      "mineral water",
      "coconut water",
    ],
    image: "/discovery/beverages.jpg",
  },
  {
    slug: "coffee-tea",
    name: "Coffee & Tea",
    description: "Roasters, private-label coffee & tea",
    keywords: [
      "coffee",
      "espresso",
      "roastery",
      "roaster",
      "matcha",
      "tea",
      "chai",
      "caffeine",
      "herbal tea",
      "green tea",
      "black tea",
      "instant coffee",
      "coffees",
      "bubble tea",
      "boba",
      "tea leaves",
    ],
    image: "/discovery/coffee-tea.jpg",
  },
  {
    slug: "bakery",
    name: "Bakery",
    description: "Wholesale bakeries, pastries & cakes",
    keywords: [
      "bakery",
      "bakeries",
      "baking",
      "cookie",
      "cookies",
      "pastry",
      "pastries",
      "tortilla",
      "bread",
      "croissant",
      "muffin",
      "muffins",
      "cake",
      "cakes",
      "cupcake",
      "cupcakes",
      "bagel",
      "bagels",
      "donut",
      "donuts",
      "doughnut",
      "scone",
      "scones",
      "brioche",
      "pie",
      "dessert",
      "cheesecake",
      "cheesecakes",
      "biscotti",
      "brownie",
      "brownies",
      "baked goods",
    ],
    image: "/discovery/bakery.jpg",
  },
  {
    slug: "meat-poultry",
    name: "Meat & Poultry",
    description: "Processors, slaughter & deli operations",
    keywords: [
      "meat",
      "poultry",
      "pork",
      "beef",
      "slaughter",
      "sausage",
      "deli meats",
      "jerky",
      "bacon",
      "ham",
      "chicken",
      "turkey",
      "brisket",
      "salami",
      "pepperoni",
      "hot dog",
      "hot dogs",
      "sausage",
      "sausages",
      "franks",
      "meatballs",
      "bratwurst",
      "butcher",
      "steak",
      "meats",
    ],
    image: "/discovery/meat-poultry.jpg",
  },
  {
    slug: "seafood",
    name: "Seafood",
    description: "Seafood processors & distributors",
    keywords: [
      "seafood",
      "shrimp",
      "salmon",
      "crab",
      "tuna",
      "fish",
      "shellfish",
      "oyster",
      "lobster",
      "cod",
      "anchovy",
      "sardine",
      "surimi",
      "fishery",
      "aquaculture",
    ],
    image: "/discovery/seafood.jpg",
  },
  {
    slug: "produce",
    name: "Produce",
    description: "Fresh & frozen fruit and vegetable handlers",
    keywords: [
      "produce",
      "fruit",
      "fruits",
      "vegetable",
      "vegetables",
      "berries",
      "avocado",
      "citrus",
      "lettuce",
      "spinach",
      "garlic",
      "onion",
      "potato",
      "potatoes",
      "tomato",
      "tomatoes",
      "grape",
      "grapes",
      "raisin",
      "raisins",
      "almond",
      "almonds",
      "walnut",
      "walnuts",
      "pecan",
      "pecans",
      "mango",
      "banana",
      "blueberry",
      "blueberries",
      "strawberry",
      "strawberries",
      "peach",
      "peaches",
      "pear",
      "pears",
      "cherry",
      "cherries",
      "watermelon",
      "cantaloupe",
      "apple",
      "salad",
    ],
    image: "/discovery/produce.jpg",
  },
  {
    slug: "snacks-sweets",
    name: "Snacks & Sweets",
    description: "Snacks, candy, confectionery & chocolate",
    keywords: [
      "snack",
      "snacks",
      "chips",
      "granola",
      "candy",
      "confection",
      "confectionery",
      "chocolate",
      "cocoa",
      "pretzel",
      "pretzels",
      "popcorn",
      "crackers",
      "trail mix",
      "nut butter",
      "sweets",
      "gummy candy",
      "lollipop",
      "lollipops",
      "caramel",
      "toffee",
      "nut",
      "nuts",
      "biscuit",
      "biscuits",
      "wafer",
      "wafers",
      "nougat",
      "brittle",
      "marshmallow",
      "marshmallows",
    ],
    image: "/discovery/snacks-sweets.jpg",
  },
  {
    slug: "sauces-seasonings",
    name: "Sauces & Seasonings",
    description: "Sauces, dressings, spices & condiments",
    keywords: [
      "sauce",
      "sauces",
      "condiment",
      "condiments",
      "salsa",
      "dressing",
      "dressings",
      "seasoning",
      "seasonings",
      "spice",
      "spices",
      "spices and seasonings",
      "marinade",
      "hot sauce",
      "ketchup",
      "mustard",
      "mayonnaise",
      "bbq sauce",
      "gravy",
      "hummus",
      "tahini",
      "vinegar",
      "olive oil",
      "rub",
      "rubs",
      "salsas",
      "dips",
      "spice blends",
    ],
    image: "/discovery/sauces-seasonings.jpg",
  },
  {
    slug: "prepared-canned",
    name: "Prepared & Canned",
    description: "Prepared meals, soups & canned goods",
    keywords: [
      "prepared meal",
      "prepared meals",
      "ready-to-eat",
      "ready to eat",
      "frozen meal",
      "frozen meals",
      "entree",
      "entrees",
      "soup",
      "soups",
      "canned",
      "canning",
      "meal kit",
      "stew",
      "broth",
      "refrigerated foods",
      "meal",
      "meals",
      "shelf-stable",
      "shelf stable",
      "ready meals",
      "heat and serve",
      "retort",
      "aseptic",
      "canned goods",
      "frozen food",
      "frozen foods",
      "chili",
    ],
    image: "/discovery/prepared-canned.jpg",
  },
  {
    slug: "grains-baking",
    name: "Grains & Baking",
    description: "Milling, flour & grain ingredients",
    keywords: [
      "grain",
      "grains",
      "milling",
      "mill",
      "flour",
      "oats",
      "oat",
      "rice",
      "pasta",
      "millet",
      "quinoa",
      "wheat",
      "barley",
      "rye",
      "semolina",
      "buckwheat",
      "cereal",
      "cornmeal",
      "bran",
      "corn",
      "soy",
      "soybean",
      "soybeans",
      "lentil",
      "lentils",
      "chickpea",
      "chickpeas",
      "bulgur",
      "couscous",
    ],
    image: "/discovery/grains-baking.jpg",
  },
  {
    slug: "nutrients-supplements",
    name: "Nutrients & Supplements",
    description: "Vitamins, gummies, protein & nutraceuticals",
    keywords: [
      "supplement",
      "supplements",
      "supplementation",
      "nutraceutical",
      "nutraceuticals",
      "vitamin",
      "vitamins",
      "probiotic",
      "probiotics",
      "collagen",
      "protein powder",
      "protein",
      "creatine",
      "prebiotic",
      "prebiotics",
      "omega",
      "capsule",
      "capsules",
      "sports nutrition",
      "gummies",
      "herbal remedy",
      "nutritional",
      "herbal",
      "botanical",
      "botanicals",
      "amino",
    ],
    image: "/discovery/nutrients-supplements.jpg",
  },
  {
    slug: "pet-food",
    name: "Pet Food",
    description: "Pet food & treat manufacturers",
    keywords: [
      "pet food",
      "pet foods",
      "pet treat",
      "pet treats",
      "pet snacks",
      "dog food",
      "cat food",
      "dog treat",
      "dog treats",
      "animal feed",
      "pet nutrition",
      "bird seed",
      // Note: no bare "pet" keyword — "PET bottles/preforms/resin" is plastic
      // packaging jargon and pulled real packaging suppliers into this aisle
      // (seen in the import report; 7 misassignments). Phrases only.
      "petfood",
      "pet care",
      "petcare",
      "pet wellness",
      "pet supplies",
      "pet supply",
      "animal nutrition",
      "pet product",
      "pet products",
      "bird food",
      "aquarium",
      "kibble",
      "dog chews",
      "cat chews",
      "dog bones",
      "cat litter",
    ],
    image: "/discovery/pet-food.jpg",
  },
  {
    slug: "health-beauty",
    name: "Health & Beauty",
    description: "Bath, body care, skincare & personal care",
    keywords: [
      "bath",
      "body care",
      "skincare",
      "skin care",
      "cosmetics",
      "cosmetic",
      "personal care",
      "soap",
      "soaps",
      "lotion",
      "lotions",
      "shampoo",
      "deodorant",
      "beauty",
      "facial",
      "spa",
      "oral care",
      "dental care",
      "hygiene",
      "hair care",
    ],
    image: "/discovery/health-beauty.jpg",
  },
  {
    slug: "packaging-services",
    name: "Packaging & Co-Pack Services",
    description: "Contract packing, co-manufacturing & packaging suppliers",
    keywords: [
      "packaging",
      "packaging supplier",
      "packaging suppliers",
      "co-packer",
      "co-packers",
      "co-packing",
      "copacking",
      "co-pack",
      "copack",
      "co-manufacturer",
      "co-manufacturers",
      "co-manufacturing",
      "contract packager",
      "contract packaging",
      "contract manufacturer",
      "private label",
      "bottling",
      "canning services",
      "filling",
      "carton",
      "cartons",
      "corrugated",
      "pouch",
      "pouches",
      "blister",
      "thermoform",
      "shrink wrap",
      "label converting",
      "flexographic",
    ],
    image: "/discovery/packaging-services.jpg",
  },
  {
    slug: OTHER_GENERAL_SLUG,
    name: "Other & General",
    description: "Suppliers that don't fit a category above",
    // Empty rule table by design: the zero-match fallback keeps every record
    // reachable and every category count honest.
    keywords: [],
    image: "/discovery/other-general.jpg",
  },
] as const;

/** All discovery slugs in card order (primary assignment candidates). */
export const DISCOVERY_CATEGORY_SLUGS: readonly string[] = DISCOVERY_CATEGORIES.map(
  (category) => category.slug,
);

export function getDiscoveryCategory(slug: string): DiscoveryCategory | undefined {
  return DISCOVERY_CATEGORIES.find((category) => category.slug === slug);
}

export function isDiscoveryCategorySlug(slug: string): boolean {
  return DISCOVERY_CATEGORY_SLUGS.includes(slug);
}
